# Generated by Django 3.2 on 2022-06-29 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KampungData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaKampung', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Populasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenisKelamin', models.CharField(choices=[('L', 'laki-laki'), ('P', 'perempuan')], default='L', max_length=1)),
                ('jumlah', models.IntegerField()),
                ('kampung_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='statistik.kampungdata')),
            ],
        ),
    ]
