# Generated by Django 3.2 on 2022-06-29 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KepalaKeluarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlahKK', models.IntegerField()),
                ('kampung_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='statistik.kampungdata')),
            ],
        ),
    ]
