# Generated by Django 3.2 on 2022-07-02 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statistik', '0002_kepalakeluarga'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kampungdata',
            old_name='namaKampung',
            new_name='nama',
        ),
    ]
