# Generated by Django 3.2 on 2022-07-30 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('statistik', '0003_rename_namakampung_kampungdata_nama'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPerKampung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_jiwa', models.IntegerField()),
                ('kk', models.IntegerField()),
                ('puskesmas', models.ImageField(upload_to='')),
                ('sekolah', models.IntegerField()),
                ('kampung_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='statistik.kampungdata')),
            ],
        ),
        migrations.RemoveField(
            model_name='populasi',
            name='kampung_id',
        ),
        migrations.DeleteModel(
            name='KepalaKeluarga',
        ),
        migrations.DeleteModel(
            name='Populasi',
        ),
    ]
