# Generated by Django 3.2 on 2022-07-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistik', '0004_auto_20220730_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataperkampung',
            name='puskesmas',
            field=models.IntegerField(),
        ),
    ]
