# Generated by Django 3.2 on 2022-07-27 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemerintah', '0003_pemerintah_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemerintah',
            name='nip',
            field=models.IntegerField(null=True),
        ),
    ]
