# Generated by Django 3.2 on 2022-07-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemerintah', '0004_alter_pemerintah_nip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemerintah',
            name='nip',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
