# Generated by Django 3.2 on 2022-07-27 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pemerintah', '0005_alter_pemerintah_nip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('struktur_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pemerintah.pemerintah')),
            ],
        ),
    ]
