# Generated by Django 3.2 on 2022-07-27 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pemerintah', '0006_organisasi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisasi',
            old_name='struktur_id',
            new_name='id_organisasi',
        ),
    ]
