# Generated by Django 3.2 on 2022-07-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemerintah', '0007_rename_struktur_id_organisasi_id_organisasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemerintah',
            name='struktur_organisasi',
            field=models.CharField(choices=[('Camat', 'CAMAT'), ('Sekretaris', 'SEKRETARIS')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='Organisasi',
        ),
    ]
