# Generated by Django 3.2 on 2022-07-28 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemerintah', '0009_organisasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pemerintah',
            name='pendidikan',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
