# Generated by Django 3.2 on 2022-07-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pemerintah', '0010_pemerintah_pendidikan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pemerintah',
            name='struktur_organisasi',
            field=models.CharField(choices=[('camat', 'CAMAT'), ('sekretaris', 'SEKRETARIS'), ('subag', 'SUBAG')], max_length=30, null=True),
        ),
    ]
