# Generated by Django 3.2 on 2022-09-06 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrasi',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
