# Generated by Django 3.2 on 2022-07-29 13:07

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=100)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('category', models.CharField(max_length=100)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('gamabar', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('slug', models.SlugField(blank=True, editable=False)),
            ],
        ),
    ]
