# Generated by Django 3.2 on 2022-08-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.BooleanField(default=False),
        ),
    ]
