# Generated by Django 3.2 on 2022-08-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
    ]
