# Generated by Django 3.2 on 2022-07-19 10:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sejarah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sejarah',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
